library(shiny)
library(shinydashboard)
library(tidyverse)
library(readxl)
library(highcharter)
library(leaflet)
library(dplyr)
library(data.table)
library(purrr)
library(scales)
source("tidycensus.R")
library("treemap")
library("viridis") 
library(knitr)
library(kableExtra)



incomeAffordability <- readRDS("Data/rds/incomeAffordability.rds")
medianSale <- readRDS("Data/rds/medianSale.rds")
neighborhoodRent <- readRDS("Data/rds/neighborhoodRent.rds")
historicalVacancy <- readRDS("Data/rds/historicalVacancy.rds")
incomeMed <- readRDS("Data/rds/incomeMed.rds")
multi <- readRDS("Data/rds/multi.rds")
allUnitsRatio <- readRDS("Data/rds/allUnitsRatio.rds")
ownersUnitsRatio <- readRDS("Data/rds/ownersUnitsRatio.rds")
rentersUnitsRatio <- readRDS("Data/rds/rentersUnitsRatio.rds")
houseAge <- readRDS("Data/rds/houseAge.rds")
costBurden <- readRDS("Data/rds/costBurden.rds")
incomeLevels <- readRDS("Data/rds/incomeLevels.rds")
averageRentsVsAffordability <- readRDS("Data/rds/averageRentsVsAffordability.rds")
wageIncreaseVsHomeSalePrice <- readRDS("Data/rds/wageIncreaseVsHomeSalePrice.rds")
wageIncreaseVsRent <- readRDS("Data/rds/wageIncreaseVsRent.rds")
