library(shiny)
library(shinydashboard)
library(tidyverse)
library(readxl)
library(highcharter)
library(leaflet)
library(dplyr)
library(data.table)
library(purrr)
library(scales)
source("tidycensus.R")
library("treemap")
library("viridis") 

# read and prepare datasources for visulization ####
incomeAffordability<-read_xlsx("Data/incomeAffordability.xlsx")
medianSale<-read.csv("Data/medianSale.csv")
neighborhoodRent<-read.csv("Data/rentAve.csv")
historicalVacancy<-read.csv("Data/vacancyHis.csv")
incomeMed<-read.csv("Data/incomeMedian.csv")
multi<-read_excel("Data/Multifamily.xlsx", sheet = "Multi-Family Listings" )
constructionTrend<-read_xlsx("Data/yearly_construction_permit_total.xlsx")
# ownerVsRenter<-read.csv("Data/housingStock_ownerVsRenter.csv")
allUnitsRatio<-read.csv("Data/allUnits.csv")
ownersUnitsRatio<-read.csv("Data/ownersUnits.csv")
rentersUnitsRatio<-read.csv("Data/rentersUnits.csv")
houseAge <- read.csv("Data/houseAge.csv")
costBurden <- read.csv("Data/costBurden.csv")
incomeLevels <- read.csv("Data/incomeLevels.csv")
averageRentsVsAffordability <- read_csv("Data/averageRentsVsAffordability.csv")
wageIncreaseVsHomeSalePrice <- read.csv("Data/wageIncreaseVsHomeSalePrice.csv")
wageIncreaseVsRent <- read.csv("Data/wageIncreaseVsRent.csv")

save.image(file = "SLCHousing.RData")
